// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFvxC8GYExGtifdZQv4GDcjDNVng2Kncs',
    appId: '1:376334215188:web:6b4eaa3de54215c2ef5f01',
    messagingSenderId: '376334215188',
    projectId: 'fintrack-65306',
    authDomain: 'fintrack-65306.firebaseapp.com',
    storageBucket: 'fintrack-65306.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlR5rBjbqu1aiiEyAwQ3jJt5o7WGqgmhs',
    appId: '1:376334215188:android:2dd858ff8039870def5f01',
    messagingSenderId: '376334215188',
    projectId: 'fintrack-65306',
    storageBucket: 'fintrack-65306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGC8Lo_ejR7zH2lueaWio6TNyDtlYOK3I',
    appId: '1:376334215188:ios:e7a1ef5e840285ffef5f01',
    messagingSenderId: '376334215188',
    projectId: 'fintrack-65306',
    storageBucket: 'fintrack-65306.firebasestorage.app',
    iosBundleId: 'com.example.finTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGC8Lo_ejR7zH2lueaWio6TNyDtlYOK3I',
    appId: '1:376334215188:ios:e7a1ef5e840285ffef5f01',
    messagingSenderId: '376334215188',
    projectId: 'fintrack-65306',
    storageBucket: 'fintrack-65306.firebasestorage.app',
    iosBundleId: 'com.example.finTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFvxC8GYExGtifdZQv4GDcjDNVng2Kncs',
    appId: '1:376334215188:web:9f09dc49d3df073cef5f01',
    messagingSenderId: '376334215188',
    projectId: 'fintrack-65306',
    authDomain: 'fintrack-65306.firebaseapp.com',
    storageBucket: 'fintrack-65306.firebasestorage.app',
  );

}